// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ColorfulText: typeof import('./src/components/ColorfulText.vue')['default']
    IMdiAlarm: typeof import('~icons/mdi/alarm')['default']
    IMdiArrowLeft: typeof import('~icons/mdi/arrow-left')['default']
    IMdiArrowRight: typeof import('~icons/mdi/arrow-right')['default']
    IMdiMoonWaningCrescent: typeof import('~icons/mdi/moon-waning-crescent')['default']
    IMdiWeatherSunny: typeof import('~icons/mdi/weather-sunny')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ToogleTheme: typeof import('./src/components/ToogleTheme.vue')['default']
  }
}
