// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Base: typeof import('./src/components/Base.vue')['default']
    IMdiAlarm: typeof import('~icons/mdi/alarm')['default']
    IMdiMoonWaningCrescent: typeof import('~icons/mdi/moon-waning-crescent')['default']
    IMdiWeatherSunny: typeof import('~icons/mdi/weather-sunny')['default']
    ToogleTheme: typeof import('./src/components/ToogleTheme.vue')['default']
  }
}
